// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfBoLK04x4-hh7lOZMmIVuyrkrY5A8UU',
    appId: '1:576062203329:web:b6156738bfb37e302abb40',
    messagingSenderId: '576062203329',
    projectId: 'appfptaskmanager',
    authDomain: 'appfptaskmanager.firebaseapp.com',
    storageBucket: 'appfptaskmanager.appspot.com',
    measurementId: 'G-ZF5YNK1CR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqKyuw77DhgkmCqO6cc95IH2e8sXMJd00',
    appId: '1:576062203329:android:8f4e0396a35badb92abb40',
    messagingSenderId: '576062203329',
    projectId: 'appfptaskmanager',
    storageBucket: 'appfptaskmanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEy32jxOo2cY_limnyFHC--qDk_FGTqD0',
    appId: '1:576062203329:ios:00b262fd6afa10f52abb40',
    messagingSenderId: '576062203329',
    projectId: 'appfptaskmanager',
    storageBucket: 'appfptaskmanager.appspot.com',
    iosBundleId: 'com.example.appfpTaskManager',
  );

}